from exceptions import ValidationError
import datetime


def validate_data_usage_policy(dataUsagePolicy):
    """
    Validates
    :param dataUsagePolicy:
    :return:
    """


def validate_license_id(licenseId):
    """

    :param licenseId:
    :return:
    """


def validate_replaces_id(replacesId):
    """

    :param replacesId:
    :return:
    """


def validate_processing_state(processingState):
    "creationDate": "2022-08-02",
    "modificationDate": "2022-08-02",
    "publishedDate": "2022-08-02",

def validate_date(date):

"private": true