from exceptions import ValidationError
import datetime


def validate_data_usage_policy(dataUsagePolicy):
    """
    Validates
    :param dataUsagePolicy:
    :return:
    """


def validate_license_id(licenseId):
    """

    :param licenseId:
    :return:
    """


def validate_replaces_id(replacesId):
    """

    :param replacesId:
    :return:
    """


def validate_processing_state(processingState):
    """

    :param processingState:
    :return:
    """
    return


def validate_date(date):

"private": true